# Generated by Django 5.2.17 on 2026-09-24 14:20

import accounts.managers
import accounts.models
import accounts.validators
import django.core.validators
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[accounts.validators.validate_school_email], verbose_name='学校邮箱')),
                ('public_code', models.CharField(default=accounts.models.generate_public_code, editable=False, max_length=11, unique=True, validators=[django.core.validators.RegexValidator('\\ACX-[A-Z0-9]{8}\\Z', '系统代号必须为 CX- 加 8 位大写字母或数字。')], verbose_name='系统代号')),
                ('wechat_id', models.CharField(blank=True, default='', max_length=64, validators=[django.core.validators.RegexValidator('\\A[A-Za-z0-9_-]+\\Z', '微信号只能包含英文字母、数字、下划线和短横线。')], verbose_name='微信号')),
                ('phone_number', models.CharField(blank=True, default='', max_length=32, validators=[django.core.validators.RegexValidator('\\A\\+?[0-9][0-9 ()-]*[0-9]\\Z', '手机号请填写数字，可带开头的 +、空格、括号和短横线。')], verbose_name='手机号')),
                ('contact_updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='联系资料更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='user_email_ci_unique'), models.CheckConstraint(condition=models.Q(('email', django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('email'))), models.Q(('email', ''), _negated=True)), name='user_email_normalized'), models.CheckConstraint(condition=models.Q(('email__regex', '^[^@\\s]+@tongji\\.edu\\.cn$')), name='user_email_school_domain'), models.CheckConstraint(condition=models.Q(('public_code__regex', '^CX-[A-Z0-9]{8}$')), name='user_public_code_format')],
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
    ]
