# Generated by Django 5.2.17 on 2026-09-24 17:38

import datetime
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500, verbose_name='处理理由')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='限制开始')),
                ('expires_at', models.DateTimeField(verbose_name='原定到期')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='提前解除时间')),
                ('revoke_reason', models.CharField(blank=True, default='', max_length=500, verbose_name='解除理由')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='处理管理员')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='提前解除管理员')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='被限制用户')),
            ],
            options={
                'verbose_name': 'UserRestriction',
                'indexes': [models.Index(fields=['user', 'expires_at'], name='g01_idx_1')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at', django.db.models.expressions.CombinedExpression(models.F('starts_at'), '+', models.Value(datetime.timedelta(days=1))))), name='userrestriction_24_hours'), models.CheckConstraint(condition=models.Q(models.Q(('revoke_reason', ''), ('revoked_at__isnull', True), ('revoked_by__isnull', True)), models.Q(('revoke_reason__regex', '\\S'), ('revoked_at__gte', models.F('starts_at')), ('revoked_at__isnull', False), ('revoked_at__lt', models.F('expires_at')), ('revoked_by__isnull', False)), _connector='OR'), name='userrestriction_revocation'), models.CheckConstraint(condition=models.Q(('reason__regex', '\\S')), name='g01_reason_nonblank')],
            },
        ),
    ]
