# Generated by Django 5.2.17 on 2026-09-24 17:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('competition_extract', 'competition_extract'), ('research_extract', 'research_extract'), ('newsletter_draft', 'newsletter_draft')], max_length=32, verbose_name='任务类型')),
                ('candidate', models.JSONField(blank=True, default=dict, verbose_name='候选字段或条目')),
                ('evidence', models.JSONField(blank=True, default=dict, verbose_name='字段/条目原文依据')),
                ('missing_fields', models.JSONField(blank=True, default=list, verbose_name='缺失字段名')),
                ('validation_errors', models.JSONField(blank=True, default=list, verbose_name='校验错误')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=12, verbose_name='处理状态')),
                ('decision_mode', models.CharField(blank=True, choices=[('', '未填写'), ('human', 'human'), ('rules', 'rules')], default='', max_length=12, verbose_name='决定方式')),
                ('rule_version', models.CharField(blank=True, default='', max_length=80, verbose_name='受控规则版本')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='作出决定时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': 'ProcessingResult',
            },
        ),
        migrations.CreateModel(
            name='SourceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='来源编码')),
                ('name', models.CharField(max_length=200, verbose_name='来源名称')),
                ('base_url', models.URLField(max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='官方入口地址')),
                ('content_kind', models.CharField(choices=[('competition', 'competition'), ('research', 'research'), ('resource', 'resource'), ('mixed', 'mixed')], max_length=20, verbose_name='内容种类')),
                ('adapter_key', models.CharField(max_length=80, verbose_name='采集适配器标识')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='维护时间')),
            ],
            options={
                'verbose_name': 'SourceConfig',
            },
        ),
        migrations.CreateModel(
            name='SourceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='原文地址')),
                ('title', models.CharField(blank=True, default='', max_length=500, verbose_name='原文标题')),
                ('body_text', models.TextField(validators=[django.core.validators.MaxLengthValidator(200000)], verbose_name='提取的原文文本')),
                ('content_hash', models.CharField(max_length=64, verbose_name='规范化文本 SHA-256')),
                ('source_published_on', models.DateField(blank=True, null=True, verbose_name='来源发布日期')),
                ('source_updated_on', models.DateField(blank=True, null=True, verbose_name='来源更新日期')),
                ('source_time_text', models.CharField(blank=True, default='', max_length=500, verbose_name='不完整时间原文')),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='首次获取时间')),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后重见时间')),
            ],
            options={
                'verbose_name': 'SourceVersion',
            },
        ),
        migrations.CreateModel(
            name='AICall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_key', models.UUIDField(default=uuid.uuid4, verbose_name='请求/重试链标识')),
                ('provider', models.CharField(max_length=50, verbose_name='服务商')),
                ('model_name', models.CharField(max_length=200, verbose_name='实际模型')),
                ('prompt_version', models.CharField(max_length=80, verbose_name='提示词版本')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='调用开始')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='调用结束')),
                ('status', models.CharField(choices=[('running', 'running'), ('succeeded', 'succeeded'), ('failed', 'failed')], default='running', max_length=12, verbose_name='状态')),
                ('duration_ms', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='耗时毫秒')),
                ('input_tokens', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='输入 token')),
                ('output_tokens', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='输出 token')),
                ('error_code', models.CharField(blank=True, default='', max_length=80, verbose_name='错误码')),
                ('error_summary', models.CharField(blank=True, default='', max_length=1000, verbose_name='脱敏错误摘要')),
            ],
            options={
                'verbose_name': 'AICall',
                'indexes': [models.Index(fields=['trace_key'], name='i06_idx_1'), models.Index(fields=['status', 'finished_at'], name='i06_idx_2')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('status', 'running')), models.Q(('finished_at__gte', models.F('started_at')), ('finished_at__isnull', False), models.Q(('status', 'running'), _negated=True)), _connector='OR'), name='aicall_finished'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'failed'), _negated=True), ('error_code__regex', '\\S'), _connector='OR'), name='aicall_error'), models.CheckConstraint(condition=models.Q(models.Q(('duration_ms__isnull', True), ('status', 'running')), models.Q(('duration_ms__isnull', False), models.Q(('status', 'running'), _negated=True)), _connector='OR'), name='aicall_duration'), models.CheckConstraint(condition=models.Q(('provider__regex', '\\S')), name='i06_provider_nonblank'), models.CheckConstraint(condition=models.Q(('model_name__regex', '\\S')), name='i06_model_name_nonblank'), models.CheckConstraint(condition=models.Q(('prompt_version__regex', '\\S')), name='i06_prompt_version_nonblank'), models.CheckConstraint(condition=models.Q(('status__in', ['running', 'succeeded', 'failed'])), name='i06_status_enum')],
            },
        ),
        migrations.CreateModel(
            name='FetchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_key', models.UUIDField(default=uuid.uuid4, verbose_name='批次标识')),
                ('requested_url', models.URLField(max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='实际请求地址')),
                ('trigger', models.CharField(choices=[('manual', 'manual'), ('scheduled', 'scheduled')], max_length=12, verbose_name='触发方式')),
                ('status', models.CharField(choices=[('running', 'running'), ('succeeded', 'succeeded'), ('unchanged', 'unchanged'), ('failed', 'failed')], default='running', max_length=16, verbose_name='运行状态')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='响应状态码')),
                ('error_code', models.CharField(blank=True, default='', max_length=80, verbose_name='错误码')),
                ('error_summary', models.CharField(blank=True, default='', max_length=1000, verbose_name='脱敏错误摘要')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='手动触发人')),
            ],
            options={
                'verbose_name': 'FetchRun',
            },
        ),
        migrations.CreateModel(
            name='ProcessingInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='输入次序')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='输入白名单快照')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='competitions.competition', verbose_name='赛事输入')),
                ('research', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='research.researchopportunity', verbose_name='科研输入')),
            ],
            options={
                'verbose_name': 'ProcessingInput',
            },
        ),
    ]
