# Generated by Django 5.2.17 on 2026-09-24 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('ingestion', '0001_initial'),
        ('newsletters', '0002_initial'),
        ('research', '0001_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processinginput',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='resources.resource', verbose_name='资源输入'),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='ai_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ingestion.aicall', verbose_name='关联 AI 调用'),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='competitions.competition', verbose_name='采纳后的赛事'),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='newsletter_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='newsletters.newsletterrevision', verbose_name='采纳后的快讯草稿版本'),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='research',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='research.researchopportunity', verbose_name='采纳后的科研'),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='确认管理员'),
        ),
        migrations.AddField(
            model_name='processinginput',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ingestion.processingresult', verbose_name='所属快讯处理结果'),
        ),
        migrations.AddField(
            model_name='sourceconfig',
            name='maintained_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='维护人'),
        ),
        migrations.AddField(
            model_name='fetchrun',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ingestion.sourceconfig', verbose_name='来源配置'),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='first_fetch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ingestion.fetchrun', verbose_name='首次获取记录'),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ingestion.sourceconfig', verbose_name='来源配置'),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='source_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ingestion.sourceversion', verbose_name='提取原文版本'),
        ),
        migrations.AddConstraint(
            model_name='processinginput',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('competition__isnull', False), ('research__isnull', True), ('resource__isnull', True)), models.Q(('competition__isnull', True), ('research__isnull', False), ('resource__isnull', True)), models.Q(('competition__isnull', True), ('research__isnull', True), ('resource__isnull', False)), _connector='OR'), name='processinginput_target'),
        ),
        migrations.AddConstraint(
            model_name='processinginput',
            constraint=models.UniqueConstraint(fields=('result', 'position'), name='processinginput_position'),
        ),
        migrations.AddConstraint(
            model_name='processinginput',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='i05_position_positive'),
        ),
        migrations.AddIndex(
            model_name='sourceconfig',
            index=models.Index(fields=['is_active', 'content_kind'], name='i01_idx_1'),
        ),
        migrations.AddConstraint(
            model_name='sourceconfig',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '\\S')), name='i01_code_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='sourceconfig',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='i01_name_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='sourceconfig',
            constraint=models.CheckConstraint(condition=models.Q(('content_kind__in', ['competition', 'research', 'resource', 'mixed'])), name='i01_content_kind_enum'),
        ),
        migrations.AddConstraint(
            model_name='sourceconfig',
            constraint=models.CheckConstraint(condition=models.Q(('content_kind__regex', '\\S')), name='i01_content_kind_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='sourceconfig',
            constraint=models.CheckConstraint(condition=models.Q(('adapter_key__regex', '\\S')), name='i01_adapter_key_nonblank'),
        ),
        migrations.AddIndex(
            model_name='fetchrun',
            index=models.Index(fields=['source', 'started_at'], name='i02_idx_1'),
        ),
        migrations.AddIndex(
            model_name='fetchrun',
            index=models.Index(fields=['status', 'finished_at'], name='i02_idx_2'),
        ),
        migrations.AddIndex(
            model_name='fetchrun',
            index=models.Index(fields=['batch_key'], name='i02_idx_3'),
        ),
        migrations.AddConstraint(
            model_name='fetchrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('status', 'running')), models.Q(('finished_at__gte', models.F('started_at')), ('finished_at__isnull', False), models.Q(('status', 'running'), _negated=True)), _connector='OR'), name='fetchrun_finished'),
        ),
        migrations.AddConstraint(
            model_name='fetchrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'failed'), _negated=True), ('error_code__regex', '\\S'), _connector='OR'), name='fetchrun_error'),
        ),
        migrations.AddConstraint(
            model_name='fetchrun',
            constraint=models.CheckConstraint(condition=models.Q(('http_status__isnull', True), models.Q(('http_status__gte', 100), ('http_status__lte', 599)), _connector='OR'), name='fetchrun_http'),
        ),
        migrations.AddConstraint(
            model_name='fetchrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('trigger', 'manual'), ('triggered_by__isnull', False)), models.Q(('trigger', 'scheduled'), ('triggered_by__isnull', True)), _connector='OR'), name='fetchrun_trigger_user'),
        ),
        migrations.AddConstraint(
            model_name='fetchrun',
            constraint=models.CheckConstraint(condition=models.Q(('trigger__in', ['manual', 'scheduled'])), name='i02_trigger_enum'),
        ),
        migrations.AddConstraint(
            model_name='fetchrun',
            constraint=models.CheckConstraint(condition=models.Q(('trigger__regex', '\\S')), name='i02_trigger_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='fetchrun',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['running', 'succeeded', 'unchanged', 'failed'])), name='i02_status_enum'),
        ),
        migrations.AddIndex(
            model_name='sourceversion',
            index=models.Index(fields=['source', 'source_url'], name='i03_idx_1'),
        ),
        migrations.AddIndex(
            model_name='sourceversion',
            index=models.Index(fields=['content_hash'], name='i03_idx_2'),
        ),
        migrations.AddConstraint(
            model_name='sourceversion',
            constraint=models.UniqueConstraint(fields=('source', 'source_url', 'content_hash'), name='sourceversion_content'),
        ),
        migrations.AddConstraint(
            model_name='sourceversion',
            constraint=models.CheckConstraint(condition=models.Q(('last_seen_at__gte', models.F('first_seen_at'))), name='sourceversion_seen_order'),
        ),
        migrations.AddConstraint(
            model_name='sourceversion',
            constraint=models.CheckConstraint(condition=models.Q(('content_hash__regex', '^[a-f0-9]{64}$')), name='sourceversion_hash'),
        ),
        migrations.AddIndex(
            model_name='processingresult',
            index=models.Index(fields=['status', 'created_at'], name='i04_idx_1'),
        ),
        migrations.AddIndex(
            model_name='processingresult',
            index=models.Index(fields=['source_version', 'created_at'], name='i04_idx_2'),
        ),
        migrations.AddIndex(
            model_name='processingresult',
            index=models.Index(fields=['task_type', 'status'], name='i04_idx_3'),
        ),
        migrations.AddConstraint(
            model_name='processingresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_version__isnull', True), ('task_type', 'newsletter_draft')), models.Q(('source_version__isnull', False), ('task_type__in', ['competition_extract', 'research_extract'])), _connector='OR'), name='processingresult_input'),
        ),
        migrations.AddConstraint(
            model_name='processingresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision_mode', ''), ('reviewed_at__isnull', True), ('reviewed_by__isnull', True), ('rule_version', ''), ('status', 'pending')), models.Q(('decision_mode', 'human'), ('reviewed_at__isnull', False), ('reviewed_by__isnull', False), ('rule_version', ''), ('status__in', ['accepted', 'rejected'])), models.Q(('decision_mode', 'rules'), ('reviewed_at__isnull', False), ('reviewed_by__isnull', True), ('status', 'accepted'), ('task_type', 'competition_extract'), models.Q(('rule_version', ''), _negated=True)), _connector='OR'), name='processingresult_decision'),
        ),
        migrations.AddConstraint(
            model_name='processingresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('status', 'accepted'), _negated=True), ('competition__isnull', True), ('newsletter_revision__isnull', True), ('research__isnull', True)), models.Q(('competition__isnull', False), ('newsletter_revision__isnull', True), ('research__isnull', True), ('status', 'accepted'), ('task_type', 'competition_extract')), models.Q(('competition__isnull', True), ('newsletter_revision__isnull', True), ('research__isnull', False), ('status', 'accepted'), ('task_type', 'research_extract')), models.Q(('competition__isnull', True), ('newsletter_revision__isnull', False), ('research__isnull', True), ('status', 'accepted'), ('task_type', 'newsletter_draft')), _connector='OR'), name='processingresult_target'),
        ),
        migrations.AddConstraint(
            model_name='processingresult',
            constraint=models.CheckConstraint(condition=models.Q(('task_type__in', ['competition_extract', 'research_extract', 'newsletter_draft'])), name='i04_task_type_enum'),
        ),
        migrations.AddConstraint(
            model_name='processingresult',
            constraint=models.CheckConstraint(condition=models.Q(('task_type__regex', '\\S')), name='i04_task_type_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='processingresult',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'accepted', 'rejected'])), name='i04_status_enum'),
        ),
        migrations.AddConstraint(
            model_name='processingresult',
            constraint=models.CheckConstraint(condition=models.Q(('decision_mode__in', ['', 'human', 'rules'])), name='i04_decision_mode_enum'),
        ),
    ]
