# Generated by Django 5.2.17 on 2026-09-24 17:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('governance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('body', models.CharField(max_length=1500, verbose_name='轻量内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='首次已读时间')),
            ],
            options={
                'verbose_name': 'Notification',
            },
        ),
        migrations.CreateModel(
            name='BusinessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='幂等事件标识')),
                ('kind', models.CharField(choices=[('recruitment_edited', 'recruitment_edited'), ('recruitment_closed', 'recruitment_closed'), ('application_submitted', 'application_submitted'), ('contact_opened', 'contact_opened'), ('application_confirmed', 'application_confirmed'), ('confirmation_revoked', 'confirmation_revoked'), ('application_continued', 'application_continued'), ('application_withdrawn', 'application_withdrawn'), ('application_rejected', 'application_rejected'), ('application_ended', 'application_ended'), ('member_joined', 'member_joined'), ('departure_requested', 'departure_requested'), ('departure_responded', 'departure_responded'), ('departure_withdrawn', 'departure_withdrawn'), ('departure_completed', 'departure_completed'), ('dissolution_requested', 'dissolution_requested'), ('dissolution_responded', 'dissolution_responded'), ('dissolution_withdrawn', 'dissolution_withdrawn'), ('dissolution_rejected', 'dissolution_rejected'), ('dissolution_completed', 'dissolution_completed'), ('admin_action', 'admin_action')], max_length=48, verbose_name='事件类型')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='事件时间')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='必要事件数据')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='动作用户')),
                ('admin_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='governance.adminaction', verbose_name='管理操作目标')),
            ],
            options={
                'verbose_name': 'BusinessEvent',
            },
        ),
    ]
