# Generated by Django 5.2.17 on 2026-09-24 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessevent',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.application', verbose_name='申请目标'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='departure_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.departurerequest', verbose_name='退出/移除目标'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='dissolution_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.dissolutionrequest', verbose_name='解散目标'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='recruitment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.recruitment', verbose_name='卡片目标'),
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='notifications.businessevent', verbose_name='业务事件'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='接收用户'),
        ),
        migrations.AddIndex(
            model_name='businessevent',
            index=models.Index(fields=['application', 'occurred_at'], name='m01_idx_2'),
        ),
        migrations.AddIndex(
            model_name='businessevent',
            index=models.Index(fields=['recruitment', 'occurred_at'], name='m01_idx_3'),
        ),
        migrations.AddConstraint(
            model_name='businessevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('admin_action__isnull', True), ('application__isnull', True), ('departure_request__isnull', True), ('dissolution_request__isnull', True), ('recruitment__isnull', False)), models.Q(('admin_action__isnull', True), ('application__isnull', False), ('departure_request__isnull', True), ('dissolution_request__isnull', True), ('recruitment__isnull', True)), models.Q(('admin_action__isnull', True), ('application__isnull', True), ('departure_request__isnull', False), ('dissolution_request__isnull', True), ('recruitment__isnull', True)), models.Q(('admin_action__isnull', True), ('application__isnull', True), ('departure_request__isnull', True), ('dissolution_request__isnull', False), ('recruitment__isnull', True)), models.Q(('admin_action__isnull', False), ('application__isnull', True), ('departure_request__isnull', True), ('dissolution_request__isnull', True), ('recruitment__isnull', True)), _connector='OR'), name='businessevent_one_target'),
        ),
        migrations.AddConstraint(
            model_name='businessevent',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['recruitment_edited', 'recruitment_closed', 'application_submitted', 'contact_opened', 'application_confirmed', 'confirmation_revoked', 'application_continued', 'application_withdrawn', 'application_rejected', 'application_ended', 'member_joined', 'departure_requested', 'departure_responded', 'departure_withdrawn', 'departure_completed', 'dissolution_requested', 'dissolution_responded', 'dissolution_withdrawn', 'dissolution_rejected', 'dissolution_completed', 'admin_action'])), name='m01_kind_enum'),
        ),
        migrations.AddConstraint(
            model_name='businessevent',
            constraint=models.CheckConstraint(condition=models.Q(('kind__regex', '\\S')), name='m01_kind_nonblank'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read_at', 'created_at'], name='m02_idx_1'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('event', 'recipient'), name='notification_once'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('read_at__isnull', True), ('read_at__gte', models.F('created_at')), _connector='OR'), name='notification_read_time'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('body__regex', '\\S')), name='m02_body_nonblank'),
        ),
    ]
