# Generated by Django 5.2.17 on 2026-09-28 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='目录编号')),
                ('version', models.PositiveSmallIntegerField(default=2026, verbose_name='目录年份')),
                ('name', models.CharField(max_length=300, verbose_name='目录原名')),
                ('grade', models.CharField(max_length=8, verbose_name='目录等级')),
                ('levels', models.CharField(max_length=100, verbose_name='目录赛事级别')),
                ('departments', models.JSONField(default=list, verbose_name='责任学院')),
                ('aliases', models.JSONField(blank=True, default=list, verbose_name='已核实名称别名')),
                ('is_active', models.BooleanField(default=True, verbose_name='纳入当前范围')),
                ('source_url', models.URLField(max_length=2048, verbose_name='目录依据')),
            ],
            options={
                'verbose_name': '学校赛事目录',
                'verbose_name_plural': '学校赛事目录',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OfficialSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048, verbose_name='监测入口')),
                ('evidence_url', models.URLField(max_length=2048, verbose_name='官网关联依据')),
                ('kind', models.CharField(choices=[('competition', '赛事官网'), ('organizer', '主办方官网'), ('campus', '校内官方通知')], default='competition', max_length=24, verbose_name='来源类型')),
                ('dedicated', models.BooleanField(default=False, verbose_name='赛事专站')),
                ('allowed_hosts', models.JSONField(default=list, verbose_name='已核对域名')),
                ('note', models.CharField(blank=True, max_length=1000, verbose_name='接入说明')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用监测')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='最近尝试')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='最近成功')),
                ('next_check_at', models.DateTimeField(blank=True, null=True, verbose_name='下次检查')),
                ('last_status', models.CharField(default='never', max_length=32, verbose_name='最近状态')),
                ('last_error', models.CharField(blank=True, max_length=1000, verbose_name='最近问题')),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('page_attempts', models.JSONField(default=dict, editable=False, verbose_name='页面轮换记录')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='competition_catalog.catalogentry')),
            ],
            options={
                'verbose_name': '官网监测入口',
                'verbose_name_plural': '官网监测入口',
                'ordering': ['entry__code', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='OfficialNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048, verbose_name='原文地址')),
                ('title', models.CharField(max_length=500, verbose_name='原文标题')),
                ('page_kind', models.CharField(choices=[('notice', '通知'), ('index', '入口快照')], default='notice', max_length=16, verbose_name='页面类型')),
                ('body', models.TextField(verbose_name='原文文本')),
                ('content_hash', models.CharField(editable=False, max_length=64)),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件链接（未解析）')),
                ('source_published_on', models.DateField(blank=True, null=True, verbose_name='原文明确发布日期')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='首次发现')),
                ('last_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='最近成功读取')),
                ('is_current_version', models.BooleanField(default=True, verbose_name='当前原文版本')),
                ('status', models.CharField(choices=[('pending', '待提取核对'), ('attachment', '关键内容在附件'), ('historical', '往届资料')], default='pending', max_length=32, verbose_name='处理状态')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notices', to='competition_catalog.officialsite')),
            ],
            options={
                'verbose_name': '官网通知原文',
                'verbose_name_plural': '官网通知原文',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitorRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='running', max_length=32)),
                ('pages', models.PositiveSmallIntegerField(default=0)),
                ('created', models.PositiveSmallIntegerField(default=0)),
                ('unchanged', models.PositiveSmallIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=1000)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='competition_catalog.officialsite')),
            ],
            options={
                'verbose_name': '官网监测记录',
                'verbose_name_plural': '官网监测记录',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.CharField(max_length=1000, verbose_name='赛事归属依据')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_bindings', to='competitions.competition')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competition_bindings', to='competition_catalog.catalogentry')),
            ],
            options={
                'verbose_name': '已发布赛事目录关联',
                'verbose_name_plural': '已发布赛事目录关联',
                'constraints': [models.UniqueConstraint(fields=('entry', 'competition'), name='catalog_competition_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='officialsite',
            constraint=models.UniqueConstraint(fields=('entry', 'url'), name='catalog_site_unique'),
        ),
        migrations.AddConstraint(
            model_name='officialnotice',
            constraint=models.UniqueConstraint(fields=('site', 'url', 'content_hash'), name='catalog_notice_version_unique'),
        ),
    ]
