# Generated by Django 5.2.17 on 2026-09-29 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_catalog', '0001_initial'),
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_hash', models.CharField(editable=False, max_length=64, verbose_name='提取时原文哈希')),
                ('candidate', models.JSONField(blank=True, default=dict, verbose_name='字段候选')),
                ('evidence', models.JSONField(blank=True, default=dict, verbose_name='字段原文依据')),
                ('missing_fields', models.JSONField(blank=True, default=list, verbose_name='缺少字段')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='提取错误')),
                ('rule_version', models.CharField(max_length=100, verbose_name='提取规则版本')),
                ('disposition', models.CharField(choices=[('ready', '可进一步核验发布'), ('review', '待补充核对'), ('irrelevant', '非赛事报名通知'), ('historical', '历史赛事')], max_length=16, verbose_name='提取结论')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('published', '已关联发布'), ('rejected', '已拒绝')], default='pending', max_length=16, verbose_name='处理状态')),
                ('decision_mode', models.CharField(blank=True, choices=[('rules', '规则复核'), ('human', '管理员复核')], default='', max_length=16, verbose_name='处理方式')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('review_note', models.CharField(blank=True, default='', max_length=1000, verbose_name='处理说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提取时间')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_extractions', to='competitions.competition', verbose_name='已发布赛事')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extractions', to='competition_catalog.officialnotice')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_catalog_extractions', to=settings.AUTH_USER_MODEL, verbose_name='维护身份')),
            ],
            options={
                'verbose_name': '官网赛事提取',
                'verbose_name_plural': '官网赛事提取',
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('notice', 'rule_version'), name='catalog_extraction_version_unique'), models.CheckConstraint(condition=models.Q(('disposition__in', ['ready', 'review', 'irrelevant', 'historical'])), name='catalog_extraction_disposition'), models.CheckConstraint(condition=models.Q(models.Q(('competition__isnull', True), ('decision_mode', ''), ('reviewed_at__isnull', True), ('reviewed_by__isnull', True), ('status', 'pending')), models.Q(('competition__isnull', False), ('decision_mode__in', ['rules', 'human']), ('reviewed_at__isnull', False), ('reviewed_by__isnull', False), ('status', 'published')), models.Q(('competition__isnull', True), ('decision_mode', 'human'), ('reviewed_at__isnull', False), ('reviewed_by__isnull', False), ('status', 'rejected')), _connector='OR'), name='catalog_extraction_decision_pair')],
            },
        ),
    ]
