# Generated by Django 5.2.17 on 2026-09-24 17:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('publish', 'publish'), ('edit', 'edit'), ('verify', 'verify'), ('withdraw', 'withdraw'), ('restore', 'restore'), ('restrict', 'restrict'), ('revoke_restriction', 'revoke_restriction'), ('disable_account', 'disable_account'), ('enable_account', 'enable_account')], max_length=32, verbose_name='操作类型')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='处理时间')),
                ('reason', models.CharField(blank=True, default='', max_length=500, verbose_name='必要理由')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='必要前后状态')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='管理员')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='competitions.competition', verbose_name='赛事目标')),
            ],
            options={
                'verbose_name': 'AdminAction',
            },
        ),
    ]
