# Generated by Django 5.2.17 on 2026-09-24 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('governance', '0001_initial'),
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaction',
            name='newsletter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='newsletters.newsletter', verbose_name='快讯目标'),
        ),
    ]
