# Generated by Django 5.2.17 on 2026-09-24 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_userrestriction'),
        ('governance', '0002_initial'),
        ('research', '0001_initial'),
        ('resources', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaction',
            name='recruitment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.recruitment', verbose_name='招募卡目标'),
        ),
        migrations.AddField(
            model_name='adminaction',
            name='research',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='research.researchopportunity', verbose_name='科研目标'),
        ),
        migrations.AddField(
            model_name='adminaction',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='resources.resource', verbose_name='资源目标'),
        ),
        migrations.AddField(
            model_name='adminaction',
            name='restriction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.userrestriction', verbose_name='关联限制记录'),
        ),
        migrations.AddField(
            model_name='adminaction',
            name='reverses',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='governance.adminaction', verbose_name='被撤销的操作'),
        ),
        migrations.AddField(
            model_name='adminaction',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='用户目标'),
        ),
        migrations.AddIndex(
            model_name='adminaction',
            index=models.Index(fields=['created_at'], name='g02_idx_1'),
        ),
        migrations.AddIndex(
            model_name='adminaction',
            index=models.Index(fields=['target_user', 'created_at'], name='g02_idx_2'),
        ),
        migrations.AddIndex(
            model_name='adminaction',
            index=models.Index(fields=['recruitment', 'created_at'], name='g02_idx_3'),
        ),
        migrations.AddConstraint(
            model_name='adminaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('competition__isnull', True), ('newsletter__isnull', True), ('recruitment__isnull', True), ('research__isnull', True), ('resource__isnull', True), ('target_user__isnull', False)), models.Q(('competition__isnull', False), ('newsletter__isnull', True), ('recruitment__isnull', True), ('research__isnull', True), ('resource__isnull', True), ('target_user__isnull', True)), models.Q(('competition__isnull', True), ('newsletter__isnull', True), ('recruitment__isnull', True), ('research__isnull', False), ('resource__isnull', True), ('target_user__isnull', True)), models.Q(('competition__isnull', True), ('newsletter__isnull', True), ('recruitment__isnull', True), ('research__isnull', True), ('resource__isnull', False), ('target_user__isnull', True)), models.Q(('competition__isnull', True), ('newsletter__isnull', False), ('recruitment__isnull', True), ('research__isnull', True), ('resource__isnull', True), ('target_user__isnull', True)), models.Q(('competition__isnull', True), ('newsletter__isnull', True), ('recruitment__isnull', False), ('research__isnull', True), ('resource__isnull', True), ('target_user__isnull', True)), _connector='OR'), name='adminaction_one_target'),
        ),
        migrations.AddConstraint(
            model_name='adminaction',
            constraint=models.CheckConstraint(condition=models.Q(('reverses__isnull', True), models.Q(('reverses', models.F('id')), _negated=True), _connector='OR'), name='adminaction_no_self'),
        ),
        migrations.AddConstraint(
            model_name='adminaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action__in', ['withdraw', 'restore', 'restrict', 'revoke_restriction', 'disable_account', 'enable_account']), _negated=True), ('reason__regex', '\\S'), _connector='OR'), name='adminaction_reason'),
        ),
        migrations.AddConstraint(
            model_name='adminaction',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['publish', 'edit', 'verify', 'withdraw', 'restore', 'restrict', 'revoke_restriction', 'disable_account', 'enable_account'])), name='g02_action_enum'),
        ),
        migrations.AddConstraint(
            model_name='adminaction',
            constraint=models.CheckConstraint(condition=models.Q(('action__regex', '\\S')), name='g02_action_nonblank'),
        ),
    ]
