# Generated by Django 5.2.17 on 2026-09-26 12:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userrestriction'),
        ('competitions', '0001_initial'),
        ('governance', '0003_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_title', models.CharField(max_length=240, verbose_name='提交时的对象名称')),
                ('description', models.CharField(max_length=1000, verbose_name='具体说明')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('feedback', models.CharField(blank=True, default='', max_length=1000, verbose_name='给提交人的处理反馈')),
                ('reason', models.CharField(choices=[('false_information', '信息不实或过期'), ('fraud', '涉嫌诈骗或不当收费'), ('inappropriate', '内容不当'), ('other', '其他问题')], max_length=24, verbose_name='问题类型')),
                ('status', models.CharField(choices=[('pending', '待核实'), ('confirmed', '问题已确认'), ('dismissed', '未确认违规')], default='pending', max_length=16, verbose_name='状态')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='competitions.competition', verbose_name='被举报赛事')),
                ('recruitment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.recruitment', verbose_name='被举报招募')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '举报',
                'verbose_name_plural': '举报',
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_title', models.CharField(max_length=240, verbose_name='提交时的对象名称')),
                ('description', models.CharField(max_length=1000, verbose_name='具体说明')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('feedback', models.CharField(blank=True, default='', max_length=1000, verbose_name='给提交人的处理反馈')),
                ('status', models.CharField(choices=[('pending', '待复核'), ('upheld', '申诉成立'), ('rejected', '申诉未获支持')], default='pending', max_length=16, verbose_name='状态')),
                ('admin_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='governance.adminaction', verbose_name='被申诉下架操作')),
                ('restriction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.userrestriction', verbose_name='被申诉限制')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='governance.report', verbose_name='被申诉举报结论')),
            ],
            options={
                'verbose_name': '申诉',
                'verbose_name_plural': '申诉',
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['submitted_by', '-created_at'], name='report_owner_time'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'created_at'], name='report_review_queue'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'confirmed', 'dismissed'])), name='report_status'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('description__regex', '\\S')), name='report_description'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('target_title__regex', '\\S')), name='report_title'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('feedback', ''), ('reviewed_at__isnull', True), ('reviewed_by__isnull', True), ('status', 'pending')), models.Q(models.Q(('status', 'pending'), _negated=True), ('feedback__regex', '\\S'), ('reviewed_at__isnull', False), ('reviewed_by__isnull', False)), _connector='OR'), name='report_review_complete'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('reviewed_at__isnull', True), ('reviewed_at__gte', models.F('created_at')), _connector='OR'), name='report_time'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('reviewed_by__isnull', True), models.Q(('reviewed_by', models.F('submitted_by')), _negated=True), _connector='OR'), name='report_not_self'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('competition__isnull', False), ('recruitment__isnull', True)), models.Q(('competition__isnull', True), ('recruitment__isnull', False)), _connector='OR'), name='report_one_target'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('reason__in', ['false_information', 'fraud', 'inappropriate', 'other'])), name='report_reason'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('competition__isnull', False), ('status', 'pending')), fields=('submitted_by', 'competition'), name='report_pending_competition'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('recruitment__isnull', False), ('status', 'pending')), fields=('submitted_by', 'recruitment'), name='report_pending_recruitment'),
        ),
        migrations.AddIndex(
            model_name='appeal',
            index=models.Index(fields=['submitted_by', '-created_at'], name='appeal_owner_time'),
        ),
        migrations.AddIndex(
            model_name='appeal',
            index=models.Index(fields=['status', 'created_at'], name='appeal_review_queue'),
        ),
        migrations.AddConstraint(
            model_name='appeal',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'upheld', 'rejected'])), name='appeal_status'),
        ),
        migrations.AddConstraint(
            model_name='appeal',
            constraint=models.CheckConstraint(condition=models.Q(('description__regex', '\\S')), name='appeal_description'),
        ),
        migrations.AddConstraint(
            model_name='appeal',
            constraint=models.CheckConstraint(condition=models.Q(('target_title__regex', '\\S')), name='appeal_title'),
        ),
        migrations.AddConstraint(
            model_name='appeal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('feedback', ''), ('reviewed_at__isnull', True), ('reviewed_by__isnull', True), ('status', 'pending')), models.Q(models.Q(('status', 'pending'), _negated=True), ('feedback__regex', '\\S'), ('reviewed_at__isnull', False), ('reviewed_by__isnull', False)), _connector='OR'), name='appeal_review_complete'),
        ),
        migrations.AddConstraint(
            model_name='appeal',
            constraint=models.CheckConstraint(condition=models.Q(('reviewed_at__isnull', True), ('reviewed_at__gte', models.F('created_at')), _connector='OR'), name='appeal_time'),
        ),
        migrations.AddConstraint(
            model_name='appeal',
            constraint=models.CheckConstraint(condition=models.Q(('reviewed_by__isnull', True), models.Q(('reviewed_by', models.F('submitted_by')), _negated=True), _connector='OR'), name='appeal_not_self'),
        ),
        migrations.AddConstraint(
            model_name='appeal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('admin_action__isnull', True), ('report__isnull', True), ('restriction__isnull', False)), models.Q(('admin_action__isnull', False), ('report__isnull', True), ('restriction__isnull', True)), models.Q(('admin_action__isnull', True), ('report__isnull', False), ('restriction__isnull', True)), _connector='OR'), name='appeal_one_target'),
        ),
        migrations.AddConstraint(
            model_name='appeal',
            constraint=models.UniqueConstraint(condition=models.Q(('restriction__isnull', False), ('status', 'pending')), fields=('submitted_by', 'restriction'), name='appeal_pending_restriction'),
        ),
        migrations.AddConstraint(
            model_name='appeal',
            constraint=models.UniqueConstraint(condition=models.Q(('admin_action__isnull', False), ('status', 'pending')), fields=('submitted_by', 'admin_action'), name='appeal_pending_action'),
        ),
        migrations.AddConstraint(
            model_name='appeal',
            constraint=models.UniqueConstraint(condition=models.Q(('report__isnull', False), ('status', 'pending')), fields=('submitted_by', 'report'), name='appeal_pending_report'),
        ),
    ]
