# Generated by Django 5.2.17 on 2026-09-24 17:38

import common.codes
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(default=common.codes.new_code('research'), max_length=80, unique=True, verbose_name='稳定编号')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)], verbose_name='基本介绍/原文说明')),
                ('summary', models.CharField(blank=True, default='', max_length=500, verbose_name='列表短摘要')),
                ('recruiting_entity', models.CharField(blank=True, default='', max_length=1000, verbose_name='招募主体原文')),
                ('official_url', models.URLField(blank=True, default='', max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='官方信息链接')),
                ('official_source_name', models.CharField(blank=True, default='', max_length=200, verbose_name='官方来源名称')),
                ('supervisor', models.CharField(blank=True, default='', max_length=200, verbose_name='可提取的导师名称')),
                ('research_group', models.CharField(blank=True, default='', max_length=200, verbose_name='可提取的课题组/实验室')),
                ('institution', models.CharField(blank=True, default='', max_length=200, verbose_name='可提取的院系/机构')),
                ('work_content', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='独立工作内容')),
                ('eligibility', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='面向对象')),
                ('requirements', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='能力要求')),
                ('vacancies_text', models.CharField(blank=True, default='', max_length=500, verbose_name='名额原文')),
                ('vacancies_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='有依据的最少名额')),
                ('vacancies_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='有依据的最多名额')),
                ('weekly_hours_text', models.CharField(blank=True, default='', max_length=500, verbose_name='投入原文')),
                ('weekly_hours_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='每周最低小时数')),
                ('weekly_hours_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='每周最高小时数')),
                ('duration_text', models.CharField(blank=True, default='', max_length=500, verbose_name='合作周期原文')),
                ('starts_on', models.DateField(blank=True, null=True, verbose_name='明确开始日期')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='明确结束日期')),
                ('collaboration_mode', models.CharField(choices=[('unknown', 'unknown'), ('online', 'online'), ('offline', 'offline'), ('hybrid', 'hybrid')], default='unknown', max_length=12, verbose_name='协作方式')),
                ('location_text', models.CharField(blank=True, default='', max_length=500, verbose_name='地点原文')),
                ('application_instructions', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='申请说明')),
                ('application_url', models.URLField(blank=True, default='', max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='可选独立报名链接')),
                ('application_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='可选公开申请邮箱')),
                ('deadline_mode', models.CharField(choices=[('unknown', 'unknown'), ('fixed', 'fixed'), ('ongoing', 'ongoing')], default='unknown', max_length=12, verbose_name='截止类型')),
                ('deadline_on', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('deadline_at', models.DateTimeField(blank=True, null=True, verbose_name='精确截止时刻')),
                ('deadline_timezone', models.CharField(blank=True, default='', max_length=64, verbose_name='来源时区')),
                ('deadline_notes', models.CharField(blank=True, default='', max_length=1000, verbose_name='截止原文与例外')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='核实结束时间')),
                ('closure_note', models.CharField(blank=True, default='', max_length=500, verbose_name='结束说明')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='最近实际核验时间')),
                ('verification_note', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='内部核验说明')),
                ('publication_status', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('withdrawn', 'withdrawn')], default='draft', max_length=12, verbose_name='发布状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='首次发布时间')),
                ('last_edited_at', models.DateTimeField(blank=True, null=True, verbose_name='最近内容编辑时间')),
                ('withdrawal_reason', models.CharField(blank=True, default='', max_length=500, verbose_name='最近下架原因')),
                ('content_version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='当前内容版本号')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='建档时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最近维护时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最近操作者')),
            ],
            options={
                'verbose_name': 'ResearchOpportunity',
            },
        ),
        migrations.CreateModel(
            name='ResearchDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='research.researchopportunity')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchTaxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='编码')),
                ('kind', models.CharField(choices=[('category', 'category'), ('tag', 'tag'), ('direction', 'direction')], max_length=12, verbose_name='用途')),
                ('name', models.CharField(max_length=80, verbose_name='名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='可供新选择')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': 'ResearchTaxonomy',
                'indexes': [models.Index(fields=['kind', 'is_active', 'sort_order'], name='r01_idx_1')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'name'), name='researchtaxonomy_kind_name'), models.CheckConstraint(condition=models.Q(('code__regex', '\\S')), name='r01_code_nonblank'), models.CheckConstraint(condition=models.Q(('kind__in', ['category', 'tag', 'direction'])), name='r01_kind_enum'), models.CheckConstraint(condition=models.Q(('kind__regex', '\\S')), name='r01_kind_nonblank'), models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='r01_name_nonblank')],
            },
        ),
        migrations.CreateModel(
            name='ResearchTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='research.researchopportunity')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='research.researchtaxonomy')),
            ],
        ),
        migrations.AddField(
            model_name='researchopportunity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='research.researchtaxonomy', verbose_name='可选分类'),
        ),
        migrations.AddField(
            model_name='researchopportunity',
            name='directions',
            field=models.ManyToManyField(blank=True, related_name='+', through='research.ResearchDirection', to='research.researchtaxonomy'),
        ),
        migrations.AddField(
            model_name='researchopportunity',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='+', through='research.ResearchTag', to='research.researchtaxonomy'),
        ),
        migrations.AddField(
            model_name='researchdirection',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='research.researchtaxonomy'),
        ),
        migrations.CreateModel(
            name='ResearchRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='版本号')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='该版完整内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='版本时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='research.researchopportunity', verbose_name='科研机会')),
            ],
            options={
                'verbose_name': 'ResearchRevision',
                'constraints': [models.UniqueConstraint(fields=('opportunity', 'version'), name='researchrevision_version'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='r04_version_positive')],
            },
        ),
        migrations.CreateModel(
            name='ResearchSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='补充链接')),
                ('source_name', models.CharField(blank=True, default='', max_length=200, verbose_name='来源名称')),
                ('source_type', models.CharField(choices=[('unknown', 'unknown'), ('official', 'official'), ('campus', 'campus')], default='unknown', max_length=16, verbose_name='来源类型')),
                ('published_on', models.DateField(blank=True, null=True, verbose_name='来源发布日期')),
                ('updated_on', models.DateField(blank=True, null=True, verbose_name='来源更新日期')),
                ('fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='最近获取时间')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='来源核验时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='research.researchopportunity', verbose_name='科研机会')),
            ],
            options={
                'verbose_name': 'ResearchSource',
                'indexes': [models.Index(fields=['opportunity', 'created_at'], name='r03_idx_1')],
                'constraints': [models.UniqueConstraint(fields=('opportunity', 'source_url'), name='researchsource_url'), models.CheckConstraint(condition=models.Q(('source_type__in', ['unknown', 'official', 'campus'])), name='r03_source_type_enum')],
            },
        ),
        migrations.AddConstraint(
            model_name='researchtag',
            constraint=models.UniqueConstraint(fields=('opportunity', 'taxonomy'), name='j07_unique_pair'),
        ),
        migrations.AddIndex(
            model_name='researchopportunity',
            index=models.Index(fields=['publication_status', 'deadline_mode', 'deadline_on'], name='r02_idx_2'),
        ),
        migrations.AddIndex(
            model_name='researchopportunity',
            index=models.Index(fields=['category', 'publication_status'], name='r02_idx_3'),
        ),
        migrations.AddIndex(
            model_name='researchopportunity',
            index=models.Index(fields=['last_verified_at'], name='r02_idx_4'),
        ),
        migrations.AddConstraint(
            model_name='researchopportunity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('publication_status', 'draft'), ('published_at__isnull', True)), models.Q(('publication_status__in', ['published', 'withdrawn']), ('published_at__isnull', False)), _connector='OR'), name='researchopportuni_pub_time'),
        ),
        migrations.AddConstraint(
            model_name='researchopportunity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('publication_status', 'withdrawn'), _negated=True), ('withdrawal_reason__regex', '\\S'), _connector='OR'), name='researchopportuni_withdrawal'),
        ),
        migrations.AddConstraint(
            model_name='researchopportunity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('publication_status', 'published'), _negated=True), models.Q(('description__regex', '\\S'), ('official_url__regex', '^https?://'), ('recruiting_entity__regex', '\\S'), ('title__regex', '\\S')), _connector='OR'), name='researchopportuni_required'),
        ),
        migrations.AddConstraint(
            model_name='researchopportunity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deadline_mode', 'fixed'), ('deadline_on__isnull', False)), models.Q(('deadline_at__isnull', True), ('deadline_mode__in', ['unknown', 'ongoing']), ('deadline_on__isnull', True), ('deadline_timezone', '')), _connector='OR'), name='researchopportuni_deadline'),
        ),
        migrations.AddConstraint(
            model_name='researchopportunity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deadline_at__isnull', True), ('deadline_timezone', '')), models.Q(('deadline_at__isnull', False), ('deadline_on__isnull', False), models.Q(('deadline_timezone', ''), _negated=True)), _connector='OR'), name='researchopportuni_time_pair'),
        ),
        migrations.AddConstraint(
            model_name='researchopportunity',
            constraint=models.CheckConstraint(condition=models.Q(('vacancies_min__isnull', True), ('vacancies_max__isnull', True), ('vacancies_min__lte', models.F('vacancies_max')), _connector='OR'), name='researchopportuni_vacancie_order'),
        ),
        migrations.AddConstraint(
            model_name='researchopportunity',
            constraint=models.CheckConstraint(condition=models.Q(('weekly_hours_min__isnull', True), ('weekly_hours_max__isnull', True), ('weekly_hours_min__lte', models.F('weekly_hours_max')), _connector='OR'), name='researchopportuni_weekly_h_order'),
        ),
        migrations.AddConstraint(
            model_name='researchopportunity',
            constraint=models.CheckConstraint(condition=models.Q(('starts_on__isnull', True), ('ends_on__isnull', True), ('starts_on__lte', models.F('ends_on')), _connector='OR'), name='researchopportuni_starts_o_order'),
        ),
        migrations.AddConstraint(
            model_name='researchopportunity',
            constraint=models.CheckConstraint(condition=models.Q(('weekly_hours_min__isnull', True), models.Q(('weekly_hours_min__gte', 0), ('weekly_hours_min__lte', 168)), _connector='OR'), name='researchopportuni_min_hours'),
        ),
        migrations.AddConstraint(
            model_name='researchopportunity',
            constraint=models.CheckConstraint(condition=models.Q(('weekly_hours_max__isnull', True), models.Q(('weekly_hours_max__gte', 0), ('weekly_hours_max__lte', 168)), _connector='OR'), name='researchopportuni_max_hours'),
        ),
        migrations.AddConstraint(
            model_name='researchopportunity',
            constraint=models.CheckConstraint(condition=models.Q(('collaboration_mode__in', ['unknown', 'online', 'offline', 'hybrid'])), name='r02_collaboration_mode_enum'),
        ),
        migrations.AddConstraint(
            model_name='researchopportunity',
            constraint=models.CheckConstraint(condition=models.Q(('deadline_mode__in', ['unknown', 'fixed', 'ongoing'])), name='r02_deadline_mode_enum'),
        ),
        migrations.AddConstraint(
            model_name='researchopportunity',
            constraint=models.CheckConstraint(condition=models.Q(('publication_status__in', ['draft', 'published', 'withdrawn'])), name='r02_publication_status_enum'),
        ),
        migrations.AddConstraint(
            model_name='researchopportunity',
            constraint=models.CheckConstraint(condition=models.Q(('content_version__gte', 1)), name='r02_content_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='researchdirection',
            constraint=models.UniqueConstraint(fields=('opportunity', 'taxonomy'), name='j08_unique_pair'),
        ),
    ]
