# Generated by Django 5.2.17 on 2026-10-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchopportunity',
            name='source_published_on',
            field=models.DateField(blank=True, null=True, verbose_name='官方原文发布日期'),
        ),
    ]
