# Generated by Django 5.2.17 on 2026-10-07 04:53

import research.presentation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_source_published_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchopportunity',
            name='card_details',
            field=models.JSONField(blank=True, default=dict, validators=[research.presentation.validate_card_details], verbose_name='结构化展示字段'),
        ),
    ]
