# Generated by Django 5.2.17 on 2026-10-02 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition_catalog', '0001_initial'),
        ('competitions', '0001_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('edition', models.CharField(blank=True, max_length=100)),
                ('sources', models.JSONField(default=list)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('content_hash', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=16)),
                ('code', models.CharField(max_length=100)),
                ('package_id', models.CharField(max_length=100)),
                ('payload_hash', models.CharField(max_length=64)),
                ('state_hash', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'code'), name='curation_imported_identity')],
            },
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(max_length=100)),
                ('package_hash', models.CharField(max_length=64)),
                ('batches', models.JSONField(default=list)),
                ('counts', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('review_status', models.CharField(choices=[('draft', '待审核'), ('approved', '已审核'), ('withdrawn', '已撤下')], default='draft', max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='curation.documentrevision')),
            ],
        ),
        migrations.AddField(
            model_name='documentrevision',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='curation.knowledgedocument'),
        ),
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='competition_catalog.catalogentry')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='competitions.competition')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='resources.resource')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='curation.documentrevision')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('catalog__isnull', False), ('competition__isnull', True), ('resource__isnull', True)), models.Q(('catalog__isnull', True), ('competition__isnull', False), ('resource__isnull', True)), models.Q(('catalog__isnull', True), ('competition__isnull', True), ('resource__isnull', False)), _connector='OR'), name='curation_one_link_target'), models.UniqueConstraint(fields=('revision', 'catalog'), name='curation_link_catalog'), models.UniqueConstraint(fields=('revision', 'competition'), name='curation_link_competition'), models.UniqueConstraint(fields=('revision', 'resource'), name='curation_link_resource')],
            },
        ),
        migrations.AddConstraint(
            model_name='knowledgedocument',
            constraint=models.CheckConstraint(condition=models.Q(('review_status__in', ['draft', 'approved', 'withdrawn'])), name='curation_review_status'),
        ),
        migrations.AddConstraint(
            model_name='documentrevision',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='curation_document_version'),
        ),
        migrations.AddConstraint(
            model_name='documentrevision',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='curation_version_positive'),
        ),
    ]
