# Generated by Django 5.2.17 on 2026-10-04 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0002_documentreview_importedobjectrevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('source_url', models.URLField(max_length=2048)),
                ('locator', models.CharField(blank=True, max_length=300)),
                ('content_hash', models.CharField(max_length=64)),
                ('text_hash', models.CharField(max_length=64)),
                ('model_id', models.CharField(max_length=160)),
                ('model_revision', models.CharField(max_length=40)),
                ('dimension', models.PositiveSmallIntegerField()),
                ('vector', models.JSONField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_chunks', to='curation.knowledgedocument')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='curation.documentrevision')),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'revision'], name='curation_chunk_current_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'revision', 'position', 'model_id', 'model_revision'), name='curation_chunk_version_unique')],
            },
        ),
    ]
