# Generated by Django 5.2.17 on 2026-10-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0002_documentreview_importedobjectrevision'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='knowledgedocument',
            name='curation_review_status',
        ),
        migrations.AlterField(
            model_name='documentreview',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('approved', '已核验'), ('withdrawn', '已撤下')], max_length=12),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='review_status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('approved', '已核验'), ('withdrawn', '已撤下')], default='draft', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='knowledgedocument',
            constraint=models.CheckConstraint(condition=models.Q(('review_status__in', ['draft', 'published', 'approved', 'withdrawn'])), name='curation_review_status'),
        ),
    ]
