# Generated by Django 5.2.17 on 2026-09-24 17:38

import common.codes
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='版本号')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='标题')),
                ('introduction', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='导读')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('confirmed', 'confirmed')], default='draft', max_length=12, verbose_name='版本状态')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='草稿创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='草稿更新时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='管理员确认时间')),
            ],
            options={
                'verbose_name': 'NewsletterRevision',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(default=common.codes.new_code('newsletter'), max_length=80, unique=True, verbose_name='稳定编号')),
                ('publication_status', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('withdrawn', 'withdrawn')], default='draft', max_length=12, verbose_name='发布状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='首次发布时间')),
                ('last_edited_at', models.DateTimeField(blank=True, null=True, verbose_name='最后公开更正时间')),
                ('withdrawal_reason', models.CharField(blank=True, default='', max_length=500, verbose_name='下架原因')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'Newsletter',
            },
        ),
        migrations.CreateModel(
            name='NewsletterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='排序')),
                ('kind', models.CharField(choices=[('competition', 'competition'), ('research', 'research'), ('resource', 'resource'), ('activity', 'activity')], max_length=16, verbose_name='条目类型')),
                ('title_snapshot', models.CharField(max_length=200, verbose_name='当期标题')),
                ('summary_snapshot', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='当期摘要/活动介绍')),
                ('source_url', models.URLField(max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='当期来源链接')),
                ('source_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='引用时业务内容时间')),
                ('source_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='引用时业务版本')),
                ('activity_time_text', models.CharField(blank=True, default='', max_length=500, verbose_name='活动时间原文')),
                ('activity_location_text', models.CharField(blank=True, default='', max_length=500, verbose_name='活动地点原文')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='competitions.competition', verbose_name='赛事引用')),
                ('research', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='research.researchopportunity', verbose_name='科研引用')),
            ],
            options={
                'verbose_name': 'NewsletterItem',
            },
        ),
    ]
