# Generated by Django 5.2.17 on 2026-09-24 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newsletters', '0001_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletteritem',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='resources.resource', verbose_name='资源引用'),
        ),
        migrations.AddField(
            model_name='newsletterrevision',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='确认管理员'),
        ),
        migrations.AddField(
            model_name='newsletterrevision',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='newsletterrevision',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='newsletters.newsletter', verbose_name='所属快讯'),
        ),
        migrations.AddField(
            model_name='newsletterrevision',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='编辑人'),
        ),
        migrations.AddField(
            model_name='newsletteritem',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='newsletters.newsletterrevision', verbose_name='所属快讯版本'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='newsletters.newsletterrevision', verbose_name='当前公开版本'),
        ),
        migrations.AddIndex(
            model_name='newsletterrevision',
            index=models.Index(fields=['newsletter', 'status'], name='n02_idx_2'),
        ),
        migrations.AddConstraint(
            model_name='newsletterrevision',
            constraint=models.UniqueConstraint(fields=('newsletter', 'version'), name='newsletterrevisio_version'),
        ),
        migrations.AddConstraint(
            model_name='newsletterrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('newsletter',), name='newsletterrevisio_one_draft'),
        ),
        migrations.AddConstraint(
            model_name='newsletterrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmed_at__isnull', True), ('confirmed_by__isnull', True), ('status', 'draft')), models.Q(('confirmed_at__isnull', False), ('confirmed_by__isnull', False), ('status', 'confirmed'), ('title__regex', '\\S')), _connector='OR'), name='newsletterrevisio_confirmed'),
        ),
        migrations.AddConstraint(
            model_name='newsletterrevision',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='n02_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='newsletterrevision',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'confirmed'])), name='n02_status_enum'),
        ),
        migrations.AddConstraint(
            model_name='newsletteritem',
            constraint=models.UniqueConstraint(fields=('revision', 'position'), name='newsletteritem_position'),
        ),
        migrations.AddConstraint(
            model_name='newsletteritem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('competition__isnull', False), ('kind', 'competition'), ('research__isnull', True), ('resource__isnull', True)), models.Q(('competition__isnull', True), ('kind', 'research'), ('research__isnull', False), ('resource__isnull', True)), models.Q(('competition__isnull', True), ('kind', 'resource'), ('research__isnull', True), ('resource__isnull', False)), models.Q(('competition__isnull', True), ('kind', 'activity'), ('research__isnull', True), ('resource__isnull', True)), _connector='OR'), name='newsletteritem_target'),
        ),
        migrations.AddConstraint(
            model_name='newsletteritem',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'activity'), models.Q(('activity_location_text', ''), ('activity_time_text', '')), _connector='OR'), name='newsletteritem_activity'),
        ),
        migrations.AddConstraint(
            model_name='newsletteritem',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='n03_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='newsletteritem',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['competition', 'research', 'resource', 'activity'])), name='n03_kind_enum'),
        ),
        migrations.AddConstraint(
            model_name='newsletteritem',
            constraint=models.CheckConstraint(condition=models.Q(('kind__regex', '\\S')), name='n03_kind_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='newsletteritem',
            constraint=models.CheckConstraint(condition=models.Q(('title_snapshot__regex', '\\S')), name='n03_title_snapshot_nonblank'),
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['publication_status', 'published_at'], name='n01_idx_1'),
        ),
        migrations.AddConstraint(
            model_name='newsletter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('publication_status', 'draft'), ('published_at__isnull', True)), models.Q(('publication_status__in', ['published', 'withdrawn']), ('published_at__isnull', False)), _connector='OR'), name='newsletter_pub_time'),
        ),
        migrations.AddConstraint(
            model_name='newsletter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('publication_status', 'withdrawn'), _negated=True), ('withdrawal_reason__regex', '\\S'), _connector='OR'), name='newsletter_withdrawal'),
        ),
        migrations.AddConstraint(
            model_name='newsletter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('publication_status', 'published'), _negated=True), ('current_revision__isnull', False), _connector='OR'), name='newsletter_revision'),
        ),
        migrations.AddConstraint(
            model_name='newsletter',
            constraint=models.CheckConstraint(condition=models.Q(('publication_status__in', ['draft', 'published', 'withdrawn'])), name='n01_publication_status_enum'),
        ),
    ]
