# Generated by Django 5.2.17 on 2026-09-24 17:38

import common.codes
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(default=common.codes.new_code('resource'), max_length=80, unique=True, verbose_name='稳定编号')),
                ('title', models.CharField(max_length=200, verbose_name='资源名称')),
                ('description', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(10000)], verbose_name='资源介绍')),
                ('provider', models.CharField(blank=True, default='', max_length=500, verbose_name='来源单位或作者')),
                ('access_url', models.URLField(blank=True, default='', max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='访问链接')),
                ('source_note', models.CharField(blank=True, default='', max_length=1000, verbose_name='来源说明')),
                ('availability', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], default='available', max_length=12, verbose_name='可用状态')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='最近实际核验时间')),
                ('publication_status', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('withdrawn', 'withdrawn')], default='draft', max_length=12, verbose_name='发布状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='首次发布时间')),
                ('last_edited_at', models.DateTimeField(blank=True, null=True, verbose_name='最近内容编辑时间')),
                ('withdrawal_reason', models.CharField(blank=True, default='', max_length=500, verbose_name='最近下架原因')),
                ('content_version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='当前内容版本号')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='建档时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最近维护时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最近操作者')),
            ],
            options={
                'verbose_name': 'Resource',
            },
        ),
        migrations.CreateModel(
            name='ResourceCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='competitions.competition')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='resources.resource')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='competitions',
            field=models.ManyToManyField(blank=True, related_name='+', through='resources.ResourceCompetition', to='competitions.competition'),
        ),
        migrations.CreateModel(
            name='ResourceResearchOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='research.researchopportunity')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='resources.resource')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='research_opportunities',
            field=models.ManyToManyField(blank=True, related_name='+', through='resources.ResourceResearchOpportunity', to='research.researchopportunity'),
        ),
        migrations.CreateModel(
            name='ResourceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='版本号')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='内容快照')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='版本时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='resources.resource', verbose_name='资源')),
            ],
            options={
                'verbose_name': 'ResourceRevision',
            },
        ),
        migrations.CreateModel(
            name='ResourceTaxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='编码')),
                ('kind', models.CharField(choices=[('category', 'category'), ('tag', 'tag'), ('direction', 'direction')], max_length=12, verbose_name='用途')),
                ('name', models.CharField(max_length=80, verbose_name='名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='可供新选择')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': 'ResourceTaxonomy',
                'indexes': [models.Index(fields=['kind', 'is_active', 'sort_order'], name='s01_idx_1')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'name'), name='resourcetaxonomy_kind_name'), models.CheckConstraint(condition=models.Q(('code__regex', '\\S')), name='s01_code_nonblank'), models.CheckConstraint(condition=models.Q(('kind__in', ['category', 'tag', 'direction'])), name='s01_kind_enum'), models.CheckConstraint(condition=models.Q(('kind__regex', '\\S')), name='s01_kind_nonblank'), models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='s01_name_nonblank')],
            },
        ),
        migrations.CreateModel(
            name='ResourceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='resources.resource')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='resources.resourcetaxonomy')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='resources.resource')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='resources.resourcetaxonomy')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='resources.resourcetaxonomy', verbose_name='资源类别'),
        ),
        migrations.AddField(
            model_name='resource',
            name='directions',
            field=models.ManyToManyField(blank=True, related_name='+', through='resources.ResourceDirection', to='resources.resourcetaxonomy'),
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='+', through='resources.ResourceTag', to='resources.resourcetaxonomy'),
        ),
        migrations.AddConstraint(
            model_name='resourcecompetition',
            constraint=models.UniqueConstraint(fields=('resource', 'competition'), name='j11_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='resourceresearchopportunity',
            constraint=models.UniqueConstraint(fields=('resource', 'opportunity'), name='j12_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='resourcerevision',
            constraint=models.UniqueConstraint(fields=('resource', 'version'), name='resourcerevision_version'),
        ),
        migrations.AddConstraint(
            model_name='resourcerevision',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='s03_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='resourcetag',
            constraint=models.UniqueConstraint(fields=('resource', 'taxonomy'), name='j09_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='resourcedirection',
            constraint=models.UniqueConstraint(fields=('resource', 'taxonomy'), name='j10_unique_pair'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['publication_status', 'availability', 'category'], name='s02_idx_1'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('publication_status', 'draft'), ('published_at__isnull', True)), models.Q(('publication_status__in', ['published', 'withdrawn']), ('published_at__isnull', False)), _connector='OR'), name='resource_pub_time'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('publication_status', 'withdrawn'), _negated=True), ('withdrawal_reason__regex', '\\S'), _connector='OR'), name='resource_withdrawal'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('publication_status', 'published'), _negated=True), models.Q(('access_url__regex', '^https?://'), ('category__isnull', False), ('description__regex', '\\S'), ('title__regex', '\\S')), _connector='OR'), name='resource_required'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.CheckConstraint(condition=models.Q(('availability__in', ['available', 'unavailable'])), name='s02_availability_enum'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.CheckConstraint(condition=models.Q(('publication_status__in', ['draft', 'published', 'withdrawn'])), name='s02_publication_status_enum'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.CheckConstraint(condition=models.Q(('content_version__gte', 1)), name='s02_content_version_positive'),
        ),
    ]
