# Generated by Django 5.2.17 on 2026-09-24 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favorites', '0001_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='resources.resource', verbose_name='资源目标'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='收藏用户'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', 'created_at'], name='f01_idx_1'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('competition__isnull', False), ('research__isnull', True), ('resource__isnull', True)), models.Q(('competition__isnull', True), ('research__isnull', False), ('resource__isnull', True)), models.Q(('competition__isnull', True), ('research__isnull', True), ('resource__isnull', False)), _connector='OR'), name='favorite_one_target'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('competition__isnull', False)), fields=('user', 'competition'), name='favorite_competition'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('research__isnull', False)), fields=('user', 'research'), name='favorite_research'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('resource__isnull', False)), fields=('user', 'resource'), name='favorite_resource'),
        ),
    ]
