# Generated by Django 5.2.17 on 2026-09-24 17:38

import common.codes
import datetime
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('contact_open', 'contact_open'), ('joined', 'joined'), ('withdrawn', 'withdrawn'), ('rejected', 'rejected'), ('ended', 'ended')], default='pending', max_length=20, verbose_name='处理阶段')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
                ('contact_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='接受并开放联系方式时间')),
                ('applicant_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='申请人当前正式确认时间')),
                ('recruiter_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='招募者当前正式确认时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='申请终结时间')),
                ('end_reason', models.CharField(blank=True, choices=[('', '未填写'), ('joined', 'joined'), ('withdrawn', 'withdrawn'), ('rejected', 'rejected'), ('recruiter_terminated', 'recruiter_terminated'), ('full', 'full'), ('expired', 'expired'), ('card_closed', 'card_closed'), ('card_withdrawn', 'card_withdrawn'), ('competition_stopped', 'competition_stopped'), ('competition_withdrawn', 'competition_withdrawn'), ('joined_other_team', 'joined_other_team'), ('team_dissolved', 'team_dissolved'), ('account_disabled', 'account_disabled')], default='', max_length=32, verbose_name='结束原因')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': 'Application',
            },
        ),
        migrations.CreateModel(
            name='ApplicationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='资料版本号')),
                ('weekly_effort', models.CharField(choices=[('up_to_2', 'up_to_2'), ('over_2_to_5', 'over_2_to_5'), ('over_5_to_10', 'over_5_to_10'), ('over_10', 'over_10')], max_length=16, verbose_name='每周可投入时间')),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='申请人接受该版条件的时间')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.application', verbose_name='所属申请')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='提交或继续的申请人')),
            ],
            options={
                'verbose_name': 'ApplicationRevision',
            },
        ),
        migrations.CreateModel(
            name='ApplicationDesiredRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teams.applicationrevision')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='applicant_confirmed_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.applicationrevision', verbose_name='申请人确认的申请版本'),
        ),
        migrations.AddField(
            model_name='application',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.applicationrevision', verbose_name='当前申请资料版本'),
        ),
        migrations.AddField(
            model_name='application',
            name='recruiter_confirmed_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.applicationrevision', verbose_name='招募者确认的申请版本'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_source', models.CharField(choices=[('recruiter', 'recruiter'), ('application', 'application')], max_length=16, verbose_name='加入来源')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='正式加入时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='成员关系结束时间')),
                ('end_reason', models.CharField(blank=True, choices=[('', '未填写'), ('exit', 'exit'), ('removal', 'removal'), ('dissolution', 'dissolution')], default='', max_length=20, verbose_name='结束方式')),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.application', verbose_name='成功申请')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='competitions.competition', verbose_name='所属赛事届次')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='成员账号')),
            ],
            options={
                'verbose_name': 'Membership',
            },
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(default=common.codes.new_code('recruitment'), max_length=80, unique=True, verbose_name='卡片编号')),
                ('publication_status', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('withdrawn', 'withdrawn')], default='draft', max_length=12, verbose_name='可见状态')),
                ('duration_days', models.PositiveSmallIntegerField(verbose_name='选择的有效天数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='建档时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='首次发布时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='本卡到期时刻')),
                ('last_edited_at', models.DateTimeField(blank=True, null=True, verbose_name='最后实际编辑时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='招募结束时间')),
                ('close_reason', models.CharField(blank=True, choices=[('', '未填写'), ('manual', 'manual'), ('expired', 'expired'), ('competition_stopped', 'competition_stopped'), ('competition_withdrawn', 'competition_withdrawn'), ('team_dissolved', 'team_dissolved')], default='', max_length=32, verbose_name='结束原因')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='最近下架时间')),
                ('withdrawal_reason', models.CharField(blank=True, default='', max_length=500, verbose_name='下架原因')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='关闭操作者')),
            ],
            options={
                'verbose_name': 'Recruitment',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='recruitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.recruitment', verbose_name='目标卡片'),
        ),
        migrations.CreateModel(
            name='RecruitmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='稳定编码')),
                ('kind', models.CharField(choices=[('role', 'role'), ('skill', 'skill'), ('campus', 'campus')], max_length=12, verbose_name='用途')),
                ('name', models.CharField(max_length=80, verbose_name='名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='可供新选择')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='顺序')),
            ],
            options={
                'verbose_name': 'RecruitmentOption',
                'indexes': [models.Index(fields=['kind', 'is_active', 'sort_order'], name='t01_idx_1')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'name'), name='recruitmentoption_kind_name'), models.CheckConstraint(condition=models.Q(('code__regex', '\\S')), name='t01_code_nonblank'), models.CheckConstraint(condition=models.Q(('kind__in', ['role', 'skill', 'campus'])), name='t01_kind_enum'), models.CheckConstraint(condition=models.Q(('kind__regex', '\\S')), name='t01_kind_nonblank'), models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='t01_name_nonblank')],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentCurrentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.recruitmentoption')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.recruitmentoption')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teams.applicationrevision')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.recruitmentoption')),
            ],
        ),
        migrations.AddField(
            model_name='applicationrevision',
            name='desired_roles',
            field=models.ManyToManyField(blank=True, related_name='+', through='teams.ApplicationDesiredRole', to='teams.recruitmentoption'),
        ),
        migrations.AddField(
            model_name='applicationrevision',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='+', through='teams.ApplicationSkill', to='teams.recruitmentoption'),
        ),
        migrations.AddField(
            model_name='applicationdesiredrole',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.recruitmentoption'),
        ),
        migrations.CreateModel(
            name='RecruitmentRequiredRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.recruitmentoption')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentRequiredSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.recruitmentoption')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='版本序号')),
                ('existing_member_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='申报已有成员数')),
                ('recruitment_quota', models.PositiveIntegerField(verbose_name='本轮计划招募人数')),
                ('foundation_requirement', models.CharField(choices=[('beginner_ok', 'beginner_ok'), ('introductory', 'introductory'), ('project_experience', 'project_experience')], max_length=24, verbose_name='基础要求')),
                ('weekly_effort', models.CharField(choices=[('up_to_2', 'up_to_2'), ('over_2_to_5', 'over_2_to_5'), ('over_5_to_10', 'over_5_to_10'), ('over_10', 'over_10')], max_length=16, verbose_name='每周投入档位')),
                ('collaboration_goal', models.CharField(blank=True, choices=[('', '未填写'), ('learning', 'learning'), ('deliver_entry', 'deliver_entry'), ('strong_result', 'strong_result')], default='', max_length=24, verbose_name='合作目标')),
                ('expected_duration', models.CharField(blank=True, choices=[('', '未填写'), ('up_to_1_month', 'up_to_1_month'), ('over_1_to_3_months', 'over_1_to_3_months'), ('over_3_to_6_months', 'over_3_to_6_months'), ('over_6_months', 'over_6_months')], default='', max_length=24, verbose_name='入队后合作时长')),
                ('collaboration_mode', models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('hybrid', 'hybrid')], max_length=12, verbose_name='协作方式')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='本版本生效时间')),
                ('campuses', models.ManyToManyField(blank=True, related_name='+', through='teams.RecruitmentCampus', to='teams.recruitmentoption')),
                ('current_skills', models.ManyToManyField(blank=True, related_name='+', through='teams.RecruitmentCurrentSkill', to='teams.recruitmentoption')),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='本次编辑人')),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.recruitment', verbose_name='所属卡片')),
                ('required_roles', models.ManyToManyField(blank=True, related_name='+', through='teams.RecruitmentRequiredRole', to='teams.recruitmentoption')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='+', through='teams.RecruitmentRequiredSkill', to='teams.recruitmentoption')),
            ],
            options={
                'verbose_name': 'RecruitmentRevision',
            },
        ),
        migrations.AddField(
            model_name='recruitmentrequiredskill',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teams.recruitmentrevision'),
        ),
        migrations.AddField(
            model_name='recruitmentrequiredrole',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teams.recruitmentrevision'),
        ),
        migrations.AddField(
            model_name='recruitmentcurrentskill',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teams.recruitmentrevision'),
        ),
        migrations.AddField(
            model_name='recruitmentcampus',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teams.recruitmentrevision'),
        ),
        migrations.CreateModel(
            name='RecruitmentBaselineMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.membership', verbose_name='计入基数的成员关系')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.recruitmentrevision', verbose_name='人数申报版本')),
            ],
            options={
                'verbose_name': 'RecruitmentBaselineMember',
            },
        ),
        migrations.AddField(
            model_name='recruitment',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.recruitmentrevision', verbose_name='当前内容版本'),
        ),
        migrations.AddField(
            model_name='applicationrevision',
            name='recruitment_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.recruitmentrevision', verbose_name='已接受的卡片版本'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(default=common.codes.new_code('team'), max_length=80, unique=True, verbose_name='稳定队伍编号')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('dissolved_at', models.DateTimeField(blank=True, null=True, verbose_name='实际解散时间')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='competitions.competition', verbose_name='所属赛事届次')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='招募者')),
            ],
            options={
                'verbose_name': 'Team',
            },
        ),
        migrations.AddField(
            model_name='recruitment',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.team', verbose_name='所属队伍'),
        ),
        migrations.AddField(
            model_name='membership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.team', verbose_name='队伍'),
        ),
        migrations.CreateModel(
            name='DissolutionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发起时间')),
                ('deadline_at', models.DateTimeField(verbose_name='回应截止')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('rejected', 'rejected'), ('withdrawn', 'withdrawn')], default='pending', max_length=16, verbose_name='结果')),
                ('completion_reason', models.CharField(blank=True, choices=[('', '未填写'), ('all_agreed', 'all_agreed'), ('timeout', 'timeout'), ('no_other_members', 'no_other_members')], default='', max_length=24, verbose_name='完成方式')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='请求结束时间')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='发起招募者')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.team', verbose_name='目标队伍')),
            ],
            options={
                'verbose_name': 'DissolutionRequest',
            },
        ),
        migrations.CreateModel(
            name='DissolutionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, choices=[('', '未填写'), ('agree', 'agree'), ('reject', 'reject')], default='', max_length=12, verbose_name='实际回应')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='回应时间')),
                ('excluded_at', models.DateTimeField(blank=True, null=True, verbose_name='因个人退出不再需回应的时间')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.dissolutionrequest', verbose_name='解散请求')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.membership', verbose_name='当时有效成员')),
            ],
            options={
                'verbose_name': 'DissolutionResponse',
                'indexes': [models.Index(fields=['request', 'response'], name='t11_idx_1'), models.Index(fields=['membership', 'request'], name='t11_idx_2')],
                'constraints': [models.UniqueConstraint(fields=('request', 'membership'), name='dissolutionrespon_pair'), models.CheckConstraint(condition=models.Q(models.Q(('responded_at__isnull', True), ('response', '')), models.Q(('responded_at__isnull', False), ('response__in', ['agree', 'reject'])), _connector='OR'), name='dissolutionrespon_response'), models.CheckConstraint(condition=models.Q(('response__in', ['', 'agree', 'reject'])), name='t11_response_enum')],
            },
        ),
        migrations.CreateModel(
            name='DepartureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('exit', 'exit'), ('removal', 'removal')], max_length=12, verbose_name='请求类型')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发起时间')),
                ('deadline_at', models.DateTimeField(verbose_name='回应截止')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('withdrawn', 'withdrawn'), ('timed_out', 'timed_out'), ('team_dissolved', 'team_dissolved')], default='pending', max_length=24, verbose_name='请求结果')),
                ('response', models.CharField(blank=True, choices=[('', '未填写'), ('agree', 'agree'), ('reject', 'reject')], default='', max_length=12, verbose_name='实际回应')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='实际回应时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='请求结束时间')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='应回应人')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.membership', verbose_name='目标成员关系')),
            ],
            options={
                'verbose_name': 'DepartureRequest',
                'indexes': [models.Index(fields=['status', 'deadline_at'], name='t09_idx_1'), models.Index(fields=['responder', 'status'], name='t09_idx_2'), models.Index(fields=['membership', 'created_at'], name='t09_idx_3')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('membership',), name='departurerequest_one_pending'), models.CheckConstraint(condition=models.Q(('initiator', models.F('responder')), _negated=True), name='departurerequest_two_parties'), models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', True), ('responded_at__isnull', True), ('response', ''), ('status', 'pending')), models.Q(('resolved_at__isnull', False), ('responded_at__isnull', False), ('response', 'agree'), ('status', 'approved')), models.Q(('resolved_at__isnull', False), ('responded_at__isnull', False), ('response', 'reject'), ('status', 'rejected')), models.Q(('resolved_at__isnull', False), ('responded_at__isnull', True), ('response', ''), ('status__in', ['withdrawn', 'timed_out', 'team_dissolved'])), _connector='OR'), name='departurerequest_outcome'), models.CheckConstraint(condition=models.Q(('deadline_at', django.db.models.expressions.CombinedExpression(models.F('created_at'), '+', models.Value(datetime.timedelta(days=1))))), name='departurerequest_deadline'), models.CheckConstraint(condition=models.Q(('resolved_at__isnull', True), ('resolved_at__gte', models.F('created_at')), _connector='OR'), name='departurerequest_end_order'), models.CheckConstraint(condition=models.Q(('kind__in', ['exit', 'removal'])), name='t09_kind_enum'), models.CheckConstraint(condition=models.Q(('kind__regex', '\\S')), name='t09_kind_nonblank'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'rejected', 'withdrawn', 'timed_out', 'team_dissolved'])), name='t09_status_enum'), models.CheckConstraint(condition=models.Q(('response__in', ['', 'agree', 'reject'])), name='t09_response_enum')],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', 'status', 'submitted_at'], name='t06_idx_1'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['recruitment', 'status'], name='t06_idx_2'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('recruitment', 'applicant'), name='application_once'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('applicant_confirmed_at__isnull', True), ('applicant_confirmed_revision__isnull', True)), models.Q(('applicant_confirmed_at__isnull', False), ('applicant_confirmed_revision__isnull', False)), _connector='OR'), name='application_applicant_pair'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('recruiter_confirmed_at__isnull', True), ('recruiter_confirmed_revision__isnull', True)), models.Q(('recruiter_confirmed_at__isnull', False), ('recruiter_confirmed_revision__isnull', False)), _connector='OR'), name='application_recruiter_pair'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_reason', ''), ('resolved_at__isnull', True), ('status__in', ['pending', 'contact_open'])), models.Q(('end_reason', 'joined'), ('resolved_at__isnull', False), ('status', 'joined')), models.Q(('end_reason', 'withdrawn'), ('resolved_at__isnull', False), ('status', 'withdrawn')), models.Q(('end_reason', 'rejected'), ('resolved_at__isnull', False), ('status', 'rejected')), models.Q(('resolved_at__isnull', False), ('status', 'ended'), models.Q(('end_reason__in', ['', 'joined', 'withdrawn', 'rejected']), _negated=True)), _connector='OR'), name='application_result'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['contact_open', 'joined']), _negated=True), ('contact_opened_at__isnull', False), _connector='OR'), name='application_contact'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'joined'), _negated=True), models.Q(('applicant_confirmed_at__isnull', False), ('applicant_confirmed_revision', models.F('current_revision')), ('current_revision__isnull', False), ('recruiter_confirmed_at__isnull', False), ('recruiter_confirmed_revision', models.F('current_revision'))), _connector='OR'), name='application_joined_confirm'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'contact_open', 'joined', 'withdrawn', 'rejected', 'ended'])), name='t06_status_enum'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('end_reason__in', ['', 'joined', 'withdrawn', 'rejected', 'recruiter_terminated', 'full', 'expired', 'card_closed', 'card_withdrawn', 'competition_stopped', 'competition_withdrawn', 'joined_other_team', 'team_dissolved', 'account_disabled'])), name='t06_end_reason_enum'),
        ),
        migrations.AddConstraint(
            model_name='applicationskill',
            constraint=models.UniqueConstraint(fields=('revision', 'option'), name='j06_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='applicationdesiredrole',
            constraint=models.UniqueConstraint(fields=('revision', 'option'), name='j05_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentrevision',
            constraint=models.UniqueConstraint(fields=('recruitment', 'version'), name='recruitmentrevisi_version'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentrevision',
            constraint=models.CheckConstraint(condition=models.Q(('existing_member_count__gte', 1)), name='recruitmentrevisi_baseline'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentrevision',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='t04_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentrevision',
            constraint=models.CheckConstraint(condition=models.Q(('existing_member_count__gte', 1)), name='t04_existing_member_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentrevision',
            constraint=models.CheckConstraint(condition=models.Q(('foundation_requirement__in', ['beginner_ok', 'introductory', 'project_experience'])), name='t04_foundation_requirem_enum'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentrevision',
            constraint=models.CheckConstraint(condition=models.Q(('foundation_requirement__regex', '\\S')), name='t04_foundation_requirem_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentrevision',
            constraint=models.CheckConstraint(condition=models.Q(('weekly_effort__in', ['up_to_2', 'over_2_to_5', 'over_5_to_10', 'over_10'])), name='t04_weekly_effort_enum'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentrevision',
            constraint=models.CheckConstraint(condition=models.Q(('weekly_effort__regex', '\\S')), name='t04_weekly_effort_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentrevision',
            constraint=models.CheckConstraint(condition=models.Q(('collaboration_goal__in', ['', 'learning', 'deliver_entry', 'strong_result'])), name='t04_collaboration_goal_enum'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentrevision',
            constraint=models.CheckConstraint(condition=models.Q(('expected_duration__in', ['', 'up_to_1_month', 'over_1_to_3_months', 'over_3_to_6_months', 'over_6_months'])), name='t04_expected_duration_enum'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentrevision',
            constraint=models.CheckConstraint(condition=models.Q(('collaboration_mode__in', ['online', 'offline', 'hybrid'])), name='t04_collaboration_mode_enum'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentrevision',
            constraint=models.CheckConstraint(condition=models.Q(('collaboration_mode__regex', '\\S')), name='t04_collaboration_mode_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentrequiredskill',
            constraint=models.UniqueConstraint(fields=('revision', 'option'), name='j03_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentrequiredrole',
            constraint=models.UniqueConstraint(fields=('revision', 'option'), name='j02_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentcurrentskill',
            constraint=models.UniqueConstraint(fields=('revision', 'option'), name='j01_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentcampus',
            constraint=models.UniqueConstraint(fields=('revision', 'option'), name='j04_unique_pair'),
        ),
        migrations.AddIndex(
            model_name='recruitmentbaselinemember',
            index=models.Index(fields=['membership', 'revision'], name='t05_idx_1'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentbaselinemember',
            constraint=models.UniqueConstraint(fields=('revision', 'membership'), name='recruitmentbaseli_pair'),
        ),
        migrations.AddConstraint(
            model_name='applicationrevision',
            constraint=models.UniqueConstraint(fields=('application', 'version'), name='applicationrevisi_version'),
        ),
        migrations.AddConstraint(
            model_name='applicationrevision',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='t07_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='applicationrevision',
            constraint=models.CheckConstraint(condition=models.Q(('weekly_effort__in', ['up_to_2', 'over_2_to_5', 'over_5_to_10', 'over_10'])), name='t07_weekly_effort_enum'),
        ),
        migrations.AddConstraint(
            model_name='applicationrevision',
            constraint=models.CheckConstraint(condition=models.Q(('weekly_effort__regex', '\\S')), name='t07_weekly_effort_nonblank'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['competition', 'dissolved_at'], name='t02_idx_1'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['recruiter', 'created_at'], name='t02_idx_2'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.CheckConstraint(condition=models.Q(('dissolved_at__isnull', True), ('dissolved_at__gte', models.F('created_at')), _connector='OR'), name='team_end_order'),
        ),
        migrations.AddIndex(
            model_name='recruitment',
            index=models.Index(fields=['team', 'created_at'], name='t03_idx_1'),
        ),
        migrations.AddIndex(
            model_name='recruitment',
            index=models.Index(fields=['publication_status', 'closed_at', 'expires_at'], name='t03_idx_2'),
        ),
        migrations.AddConstraint(
            model_name='recruitment',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True), ('publication_status', 'published')), fields=('team',), name='recruitment_one_open'),
        ),
        migrations.AddConstraint(
            model_name='recruitment',
            constraint=models.CheckConstraint(condition=models.Q(('duration_days__in', [3, 7, 14])), name='recruitment_duration'),
        ),
        migrations.AddConstraint(
            model_name='recruitment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('publication_status', 'draft'), ('published_at__isnull', True)), models.Q(('current_revision__isnull', False), ('expires_at__isnull', False), ('publication_status__in', ['published', 'withdrawn']), ('published_at__isnull', False)), _connector='OR'), name='recruitment_published'),
        ),
        migrations.AddConstraint(
            model_name='recruitment',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), models.Q(('expires_at__gt', models.F('published_at')), ('published_at__isnull', False)), _connector='OR'), name='recruitment_expiry'),
        ),
        migrations.AddConstraint(
            model_name='recruitment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('close_reason', ''), ('closed_at__isnull', True)), models.Q(('closed_at__isnull', False), models.Q(('close_reason', ''), _negated=True)), _connector='OR'), name='recruitment_close_pair'),
        ),
        migrations.AddConstraint(
            model_name='recruitment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('publication_status', 'withdrawn'), _negated=True), models.Q(('withdrawal_reason__regex', '\\S'), ('withdrawn_at__isnull', False)), _connector='OR'), name='recruitment_withdrawn'),
        ),
        migrations.AddConstraint(
            model_name='recruitment',
            constraint=models.CheckConstraint(condition=models.Q(('publication_status__in', ['draft', 'published', 'withdrawn'])), name='t03_publication_status_enum'),
        ),
        migrations.AddConstraint(
            model_name='recruitment',
            constraint=models.CheckConstraint(condition=models.Q(('close_reason__in', ['', 'manual', 'expired', 'competition_stopped', 'competition_withdrawn', 'team_dissolved'])), name='t03_close_reason_enum'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['team', 'ended_at'], name='t08_idx_1'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('user', 'competition'), name='membership_one_active'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('application__isnull', True), ('join_source', 'recruiter')), models.Q(('application__isnull', False), ('join_source', 'application')), _connector='OR'), name='membership_source'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_reason', ''), ('ended_at__isnull', True)), models.Q(('ended_at__gte', models.F('joined_at')), ('ended_at__isnull', False), models.Q(('end_reason', ''), _negated=True)), _connector='OR'), name='membership_end_pair'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('join_source__in', ['recruiter', 'application'])), name='t08_join_source_enum'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('join_source__regex', '\\S')), name='t08_join_source_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('end_reason__in', ['', 'exit', 'removal', 'dissolution'])), name='t08_end_reason_enum'),
        ),
        migrations.AddIndex(
            model_name='dissolutionrequest',
            index=models.Index(fields=['status', 'deadline_at'], name='t10_idx_1'),
        ),
        migrations.AddIndex(
            model_name='dissolutionrequest',
            index=models.Index(fields=['team', 'created_at'], name='t10_idx_2'),
        ),
        migrations.AddConstraint(
            model_name='dissolutionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('team',), name='dissolutionreques_one_pending'),
        ),
        migrations.AddConstraint(
            model_name='dissolutionrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completion_reason', ''), ('resolved_at__isnull', True), ('status', 'pending')), models.Q(('completion_reason', ''), ('resolved_at__isnull', False), ('status__in', ['rejected', 'withdrawn'])), models.Q(('resolved_at__isnull', False), ('status', 'completed'), models.Q(('completion_reason', ''), _negated=True)), _connector='OR'), name='dissolutionreques_outcome'),
        ),
        migrations.AddConstraint(
            model_name='dissolutionrequest',
            constraint=models.CheckConstraint(condition=models.Q(('deadline_at', django.db.models.expressions.CombinedExpression(models.F('created_at'), '+', models.Value(datetime.timedelta(days=1))))), name='dissolutionreques_deadline'),
        ),
        migrations.AddConstraint(
            model_name='dissolutionrequest',
            constraint=models.CheckConstraint(condition=models.Q(('resolved_at__isnull', True), ('resolved_at__gte', models.F('created_at')), _connector='OR'), name='dissolutionreques_end_order'),
        ),
        migrations.AddConstraint(
            model_name='dissolutionrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'completed', 'rejected', 'withdrawn'])), name='t10_status_enum'),
        ),
        migrations.AddConstraint(
            model_name='dissolutionrequest',
            constraint=models.CheckConstraint(condition=models.Q(('completion_reason__in', ['', 'all_agreed', 'timeout', 'no_other_members'])), name='t10_completion_reason_enum'),
        ),
    ]
