# Generated by Django 5.2.17 on 2026-09-24 14:20

import competitions.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionTaxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('\\A[a-z0-9]+(?:-[a-z0-9]+)*\\Z', '编码请使用小写字母、数字及分隔用短横线。')], verbose_name='词条编码')),
                ('kind', models.CharField(choices=[('category', '主分类'), ('tag', '标签')], max_length=20, verbose_name='词条用途')),
                ('name', models.CharField(max_length=50, verbose_name='展示名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='可供新选择')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='展示顺序')),
            ],
            options={
                'verbose_name': '赛事分类或标签',
                'verbose_name_plural': '赛事分类与标签',
                'ordering': ('sort_order', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('code__regex', '^[a-z0-9]+(-[a-z0-9]+)*$'), models.Q(('code__regex', '\\s'), _negated=True)), name='comp_taxonomy_code_format'), models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='comp_taxonomy_name_notblank'), models.CheckConstraint(condition=models.Q(('kind__in', ['category', 'tag'])), name='comp_taxonomy_kind'), models.UniqueConstraint(fields=('kind', 'name'), name='comp_taxonomy_kind_name_unique')],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True, validators=[django.core.validators.RegexValidator('\\A[a-z0-9]+(?:-[a-z0-9]+)*\\Z', '编码请使用小写字母、数字及分隔用短横线。')], verbose_name='稳定编码')),
                ('title', models.CharField(max_length=200, verbose_name='赛事名称')),
                ('edition', models.CharField(max_length=80, verbose_name='年度或届次')),
                ('summary', models.CharField(blank=True, default='', max_length=500, verbose_name='列表简介')),
                ('description', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)], verbose_name='赛事详情')),
                ('level', models.CharField(choices=[('unknown', '未注明'), ('international', '国际'), ('national', '全国'), ('provincial', '省级'), ('municipal', '市级'), ('university', '校级'), ('college', '院系级'), ('other', '其他')], default='unknown', max_length=20, verbose_name='赛事范围')),
                ('organizer', models.CharField(blank=True, default='', max_length=500, verbose_name='主办方')),
                ('tracks', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='赛道说明')),
                ('eligibility', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='参赛资格')),
                ('participation_type', models.CharField(choices=[('unknown', '未说明'), ('individual', '个人赛'), ('team', '团队赛'), ('both', '同时允许个人与团队')], default='unknown', max_length=20, verbose_name='参赛形式')),
                ('team_size_min', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='官方团队人数下限')),
                ('team_size_max', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='官方团队人数上限')),
                ('registration_method', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='官方报名方式')),
                ('registration_url', models.URLField(blank=True, default='', max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='官方报名入口')),
                ('campus_arrangements', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='同济校内安排')),
                ('registration_deadline', models.DateField(blank=True, null=True, verbose_name='报名截止日期')),
                ('registration_deadline_at', models.DateTimeField(blank=True, null=True, verbose_name='报名截止时刻')),
                ('registration_deadline_timezone', models.CharField(blank=True, default='', max_length=64, validators=[competitions.validators.validate_source_timezone], verbose_name='报名截止来源时区')),
                ('submission_deadline', models.DateField(blank=True, null=True, verbose_name='作品提交截止日期')),
                ('submission_deadline_at', models.DateTimeField(blank=True, null=True, verbose_name='作品提交截止时刻')),
                ('submission_deadline_timezone', models.CharField(blank=True, default='', max_length=64, validators=[competitions.validators.validate_source_timezone], verbose_name='作品提交来源时区')),
                ('campus_deadline', models.DateField(blank=True, null=True, verbose_name='校内截止日期')),
                ('campus_deadline_at', models.DateTimeField(blank=True, null=True, verbose_name='校内截止时刻')),
                ('campus_deadline_timezone', models.CharField(blank=True, default='', max_length=64, validators=[competitions.validators.validate_source_timezone], verbose_name='校内截止来源时区')),
                ('deadline_notes', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='截止时间说明')),
                ('publication_status', models.CharField(choices=[('draft', '草稿'), ('published', '已公开'), ('withdrawn', '已下架')], default='draft', max_length=20, verbose_name='发布状态')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='首次发布时间')),
                ('withdrawal_reason', models.CharField(blank=True, default='', max_length=500, verbose_name='最近下架原因')),
                ('last_verified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='整条核验时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建档时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='内容更新时间')),
                ('recruitment_enabled', models.BooleanField(default=False, verbose_name='开放站内招募')),
                ('recruitment_deadline', models.DateTimeField(blank=True, null=True, verbose_name='平台招募截止')),
                ('recruitment_note', models.CharField(blank=True, default='', max_length=1000, verbose_name='招募期限核验依据')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_competitions', to=settings.AUTH_USER_MODEL, verbose_name='建档人')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_competitions', to=settings.AUTH_USER_MODEL, verbose_name='最近修改人')),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'kind': 'category'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorized_competitions', to='competitions.competitiontaxonomy', verbose_name='主分类')),
                ('tags', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'kind': 'tag'}, related_name='tagged_competitions', to='competitions.competitiontaxonomy', verbose_name='标签')),
            ],
            options={
                'verbose_name': '赛事届次',
                'verbose_name_plural': '赛事届次',
                'ordering': ('-published_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CompetitionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('official', '赛事官方'), ('campus', '校内官方')], max_length=20, verbose_name='来源类型')),
                ('source_name', models.CharField(max_length=200, verbose_name='来源名称')),
                ('source_url', models.URLField(max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='原文链接')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主来源')),
                ('source_published_on', models.DateField(blank=True, null=True, verbose_name='原通知发布日期')),
                ('source_updated_on', models.DateField(blank=True, null=True, verbose_name='原通知更新日期')),
                ('fetched_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='最近成功采集时间')),
                ('last_verified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='来源核验时间')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='competitions.competition', verbose_name='赛事届次')),
            ],
            options={
                'verbose_name': '赛事来源',
                'verbose_name_plural': '赛事来源',
                'ordering': ('-is_primary', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('competition',), name='comp_one_primary_source'), models.CheckConstraint(condition=models.Q(('source_name__regex', '\\S')), name='comp_source_name_notblank'), models.CheckConstraint(condition=models.Q(('source_type__in', ['official', 'campus'])), name='comp_source_type_valid'), models.CheckConstraint(condition=models.Q(('source_url__regex', '^https?://')), name='comp_source_http_url')],
            },
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['publication_status', 'published_at', 'id'], name='comp_status_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['publication_status', 'registration_deadline', 'id'], name='comp_status_deadline_idx'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '^[a-z0-9]+(-[a-z0-9]+)*$'), models.Q(('code__regex', '\\s'), _negated=True)), name='competition_code_format'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(('title__regex', '\\S')), name='competition_title_notblank'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(('edition__regex', '\\S')), name='competition_edition_notblank'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(('level__in', ['unknown', 'international', 'national', 'provincial', 'municipal', 'university', 'college', 'other'])), name='comp_level_valid'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(('participation_type__in', ['unknown', 'individual', 'team', 'both'])), name='comp_participation_valid'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(('publication_status__in', ['draft', 'published', 'withdrawn'])), name='comp_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(('team_size_min__isnull', True), ('team_size_min__gte', 1), _connector='OR'), name='comp_team_min_positive'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(('team_size_max__isnull', True), ('team_size_max__gte', 1), _connector='OR'), name='comp_team_max_positive'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(('team_size_min__isnull', True), ('team_size_max__isnull', True), ('team_size_min__lte', models.F('team_size_max')), _connector='OR'), name='comp_team_size_order'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('participation_type', 'individual'), _negated=True), models.Q(('recruitment_enabled', False), ('team_size_max__isnull', True), ('team_size_min__isnull', True)), _connector='OR'), name='comp_individual_without_team'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('publication_status', 'draft'), ('published_at__isnull', True)), models.Q(('publication_status__in', ['published', 'withdrawn']), ('published_at__isnull', False)), _connector='OR'), name='comp_status_publication_time'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('publication_status', 'published'), _negated=True), models.Q(('category__isnull', False), ('description__regex', '\\S'), ('last_verified_at__isnull', False), ('summary__regex', '\\S')), _connector='OR'), name='comp_published_fields_present'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('publication_status', 'withdrawn'), _negated=True), ('withdrawal_reason__regex', '\\S'), _connector='OR'), name='comp_withdrawal_reason_present'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(('recruitment_enabled', False), models.Q(('participation_type__in', ['team', 'both']), ('publication_status', 'published'), ('recruitment_deadline__isnull', False), ('recruitment_note__regex', '\\S')), _connector='OR'), name='comp_recruitment_requirements'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(('registration_deadline__isnull', False), models.Q(('registration_deadline_at__isnull', True), ('registration_deadline_timezone', '')), _connector='OR'), name='comp_registration_deadline_day_pair'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(('registration_deadline_at__isnull', True), models.Q(('registration_deadline__isnull', False), models.Q(('registration_deadline_timezone', ''), _negated=True)), _connector='OR'), name='comp_registration_deadline_at_pair'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(('submission_deadline__isnull', False), models.Q(('submission_deadline_at__isnull', True), ('submission_deadline_timezone', '')), _connector='OR'), name='comp_submission_deadline_day_pair'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(('submission_deadline_at__isnull', True), models.Q(('submission_deadline__isnull', False), models.Q(('submission_deadline_timezone', ''), _negated=True)), _connector='OR'), name='comp_submission_deadline_at_pair'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(('campus_deadline__isnull', False), models.Q(('campus_deadline_at__isnull', True), ('campus_deadline_timezone', '')), _connector='OR'), name='comp_campus_deadline_day_pair'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(('campus_deadline_at__isnull', True), models.Q(('campus_deadline__isnull', False), models.Q(('campus_deadline_timezone', ''), _negated=True)), _connector='OR'), name='comp_campus_deadline_at_pair'),
        ),
    ]
