# Generated by Django 5.2.17 on 2026-10-03 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='competition',
            name='comp_published_fields_present',
        ),
        migrations.AddField(
            model_name='competition',
            name='publication_method',
            field=models.CharField(choices=[('verified', '核验后发布'), ('direct', '直接发布')], default='verified', editable=False, max_length=20, verbose_name='发布方式'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(('publication_method__in', ['verified', 'direct'])), name='comp_publication_method_valid'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('publication_status', 'published'), _negated=True), models.Q(('category__isnull', False), ('description__regex', '\\S'), ('summary__regex', '\\S'), models.Q(('publication_method', 'direct'), ('last_verified_at__isnull', False), _connector='OR')), _connector='OR'), name='comp_published_fields_present'),
        ),
    ]
