# Generated by Django 5.2.17 on 2026-10-06 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_direct_publication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='competition',
            name='comp_recruitment_requirements',
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(('recruitment_enabled', False), models.Q(('participation_type__in', ['team', 'both', 'unknown']), ('publication_status', 'published'), ('recruitment_note__regex', '\\S')), _connector='OR'), name='comp_recruitment_requirements'),
        ),
    ]
